__PANEL_DOMAIN__ {
  reverse_proxy 127.0.0.1:5180
}

__FORM_DOMAIN__ {
  reverse_proxy 127.0.0.1:5180
}

__GALLERY_DOMAIN__ {
  reverse_proxy 127.0.0.1:5180
}

__IMAGES_DOMAIN__ {
  reverse_proxy 127.0.0.1:5180
}
